version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - app-network
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=todoapp
      - DB_USERNAME=todouser
      - DB_PASSWORD=todopassword
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=todoapp
      - MYSQL_USER=todouser
      - MYSQL_PASSWORD=todopassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: 